### ISSUE TITLE
Sniffing outside a region 

### ISSUE THREAD

**Issue by demontolivo** [ninjhacks/gsmevil2#11]
Please can I use Gsmevil2 and sniff sms from numbers outsides my country ? Or is it within my region or country only ? If it’s possible to use it to capture sms from numbers outside my country. Pls I would love to know how. Thanks

**Comment by ninjhacks** [comment]
It does not work like that it's just a tool that captures sms packets from gsm traffic you capture using your SDR hardware with help of tools like gr gsm & it only works if there is no encryption on traffic.
