### ISSUE TITLE
the SMS sniffer is not working ! 

### ISSUE THREAD

**Issue by darkhacknet** [ninjhacks/gsmevil2#12]
Hello dude ! 

Would you be so kind to help me ? I dont know much about this but finally the gsmevil2 is working. I've set everything with no errors during the process ! But I've noticed that the SMS sniffer is not working, even seems to be disabled ! I dont know why, but I need to mention that Im sniffing PCS band, and this could be the problem, please confirm. 

Thanks in advance.

**Comment by ChillVibesMushroom** [comment]
hello how did you get grgsm_livemon to work and what band are you using are you using 2g 3g 4g 4g lte :)

**Comment by darkhacknet** [comment]
> hello how did you get grgsm_livemon to work and what band are you using are you using 2g 3g 4g 4g lte :)

Now its working fine thanks..

**Comment by ChillVibesMushroom** [comment]
> > hello how did you get grgsm_livemon to work and what band are you using are you using 2g 3g 4g 4g lte :)
> 
> Now its working fine thanks..

What was wrong

**Comment by ChillVibesMushroom** [comment]
I try to sniff and get no traffic sadly

**Comment by ninjhacks** [comment]
> I try to sniff and get no traffic sadly
Use kalibrate to find correct frequency.

**Comment by darkhacknet** [comment]
> > I try to sniff and get no traffic sadly
> Use kalibrate to find correct frequency.

Man I said to the other guy that my command is working fine, but the sms sniffer is not working.. Im only getting imsis but not sms. Could you Please help.? Thanks in advance.

**Comment by ninjhacks** [comment]
It's will show SMS only if there is not any encryption.

**Comment by darkhacknet** [comment]
> It's will show SMS only if there is not any encryption.

ooooh damn bro thanks, of course the information is encypted. So do you know what can I do ? Im looking for specific data like MSC also global title and stuff like that. 

Thanks for your answer ! Regards

**Comment by ChillVibesMushroom** [comment]
You're able to capture imsi information ? What command are you using. And
yeah there are such things as downgrade attacks but idk how to do them

**Comment by ChillVibesMushroom** [comment]
> It's will show SMS only if there is not any encryption.

I run Gsmevil2 and can capture PCS1900 traffic which is encrypted but I can't get imsi info or sms info so I just put my phone on 2G or z3G right then look for the right frequency? 

I have a hackrfone I'm able to capture traffic it's just Gsmevil2 doesn't show anything and I even delete imsi.db because supposedly that's a fix for dragonosfocal 


Basically what I'm asking is do I have to put my phone on 2G or 3 G

**Comment by ninjhacks** [comment]
> I run Gsmevil2 and can capture PCS1900 traffic which is encrypted but I can't get imsi info or sms info so I just put my phone on 2G or z3G right then look for the right frequency?
> 
> I have a hackrfone I'm able to capture traffic it's just Gsmevil2 doesn't show anything and I even delete imsi.db because supposedly that's a fix for dragonosfocal
> 
> check in wireshark you getting imsi or not.

**Comment by ChillVibesMushroom** [comment]
I am getting IMSI information
