### ISSUE TITLE
Unable to capture Sms

### ISSUE THREAD

**Issue by Gourav9111** [ninjhacks/gsmevil2#18]
I try a lot of time but it unable to capture Sms and I use drogon os operating system please solve this issue

**Comment by ninjhacks** [comment]
if you getting imsi & not sms chances are there is encryption.

**Comment by Gourav9111** [comment]
I got imsi but not getting any sms and I use first frequency 946.8 MHz please share any new updates so I capture it

**Comment by ninjhacks** [comment]
more active on discord.gg/ninjhacks
