### ISSUE TITLE
Unsupported version of the Socket.IO

### ISSUE THREAD

**Issue by VitalijKo** [ninjhacks/gsmevil2#9]
I installed all latest versions of requirement. When i start GSMEvil, there is a warning. The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO). How can i fix that error?

**Comment by dd121** [comment]
> I installed all latest versions of requirement. When i start GSMEvil, there is a warning. The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO). How can i fix that error?

same

**Comment by cpeter79** [comment]
In which step this error appears? I configured all with HackRF antenna and all is working pretty fine.

If you want, we can talk about it in telegram and discuss the conditions. https://t.me/p1_hk

**Comment by maikdf84** [comment]
Same error, any solution? thanks

**Comment by ninjhacks** [comment]
I think the reason is you using a newer version of python or packages if you wanna me to look into this issue you can join me at discord https://discord.gg/zyUThM4

**Comment by darkhacknet** [comment]
> In which step this error appears? I configured all with HackRF antenna and all is working pretty fine.
> 
> If you want, we can talk about it in telegram and discuss the conditions. https://t.me/p1_hk

Always trying to make money! buuu !

**Comment by darkhacknet** [comment]
> I think the reason is you using a newer version of python or packages if you wanna me to look into this issue you can join me at discord https://discord.gg/zyUThM4

Man thanks but is almost impossible to contact you via discord, your server has a bunch of stuff, and seems to be hard to contact you. That's my impression !

**Comment by pixkike** [comment]
Same Please Help Someone

**Comment by ninjhacks** [comment]
fixed in new version 2.1.0
